### ISSUE TITLE
ContactsListFragment with Contacts ContentProvider

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#9] opened 2015-03-05 04:59 UTC
- [ ] List of all your accepted contacts from Parse
- [ ] Grab all your Contacts from ContentProvider
- [ ] Match profiles from ContentProvider to Contacts

**Comment by rtteal** [comment] 2015-03-07 18:36
Looks like a duplicate of #10

**Closed as completed** 2015-03-07 18:35 UTC
Labels: duplicate
